version: "3.3"

services:
  backend:
    build:
      context: CV
      dockerfile: dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: next
      dockerfile: dockerfile
    ports:
      - "3000:3000"
